import { Button, VerticalBox, AboutSlint, HorizontalBox } from "std-widgets.slint";

component RepeatedImage {
    //preferred-height: 100%;
    //preferred-width: 100%;
    in property <image> source;
    in property <color> colorize;
    Rectangle {
        clip: true;
        HorizontalLayout {
            for _ in 10 : VerticalLayout {
                for _ in 10 : Image {
                    source: root.source;
                    colorize: root.colorize;
                }
            }
        }
    }
}

export component AppWindow inherits Window {
    in-out property <bool> logged_in: false;
    in-out property <string> uid: "";
    in-out property <string> name: "";
    in-out property <int> credits: -1;
    in-out property <image> profile_picture: @image-url("./scan-id.svg");
    in-out property <int> radius;
    private property <float> tick_2s: mod(animation-tick(), 2s) / 2s;
    private property <float> tick_5s: mod(animation-tick(), 5s) / 5s;
    private property <float> tick_20s: mod(animation-tick(), 20s) / 20s;
    out property <duration> session_duration: 30s;
    out property <duration> tick: animation-tick();
    in-out property <duration> offset: 0;
    out property <float> logout_time: logged_in ? (mod(animation-tick() - offset, session_duration) / session_duration) : 0.999999;
    no-frame: true;
    default-font-family: "DejaVu Sans";
    default-font-size: 35px;
    default-font-weight: 800;

    Rectangle {
        background: #B0197E;
        Image {
            height: (self.opacity > 0 ? sin(tick_2s * 360deg) * 50px : 0px) + 300px;
            source: @image-url("./scan-id.svg");
            colorize: white;
            vertical-alignment: center;
            //opacity: logged_in ? 0 : 1;

            animate opacity {
                easing: ease-in;
                duration: 300ms;
            }
        }
    }

    circle := Path {
        fill: #41013C;
        width: logged_in ? 400% : 0%;
        height: logged_in ? 400% : 0%;
        x: parent.width - self.width / 2;
        y: parent.height - self.height / 2;

        animate width {
            delay: 100ms;
            duration: 1000ms;
            easing: ease-in-out;
        }

        animate height {
            delay: 100ms;
            duration: 1000ms;
            easing: ease-in-out;
        }

        MoveTo {
            x: -1;
            y: 0;
        }

        ArcTo {
            radius-x: 1;
            radius-y: 1;
            sweep: true;
            large-arc: false;
            x: 2;
            y: 0;
        }
    }

    Rectangle {
        opacity: circle.width > parent.width * 3 ? 1 : 0;

        animate opacity {
            duration: 100ms;
            easing: linear;
        }

        RepeatedImage {
            source: @image-url("./csh-tile.svg");
            colorize: #380033;
            y: (tick_5s * 400px) - 400px;
            x: (tick_20s * -400px);
        }


        HorizontalLayout {
            alignment: center;

            VerticalLayout {
                alignment: center;

                Rectangle {

                    HorizontalLayout {
                        padding: 16px;
                        padding-left: 0px;

                        alignment: start;
                        Rectangle {
                            Rectangle {
                                clip: true;
                                background: #41013C;
                                border-radius: 20px;
                                width: 256px;
                                height: 256px;

                                Image {
                                    source: profile_picture;
                                    width: 256px;
                                    height: 256px;
                                    horizontal-alignment: center;
                                }
                            }
                        }

                        VerticalLayout {
                            alignment: start;
                            HorizontalLayout {
                                alignment: start;
                                spacing: 8px;

                                Text {
                                    text: name;
                                    color: white;
                                }

                                Text {
                                    text: "(" + uid + ")";
                                    color: gray;
                                }
                            }

                            Text {
                                text: credits + " Credit" + (credits > 1 ? "s" : "");
                                color: white;
                                font-weight: 400;
                            }
                        }
                    }
                }
            }
        }


        Rectangle {
            x: root.width - self.width - 20px;
            y: 20px;

            width: 100px;
            height: 100px;

            Text {
                text: floor(((1 - logout_time) * session_duration) / 1s);
                color: #ffffff;
            }

            Path {
                stroke-width: 10px;
                stroke: #6b6b6b;
                viewbox-x: 0;
                viewbox-y: 0;
                viewbox-width: 10;
                viewbox-height: 10;
                
                MoveTo {
                    x: 5;
                    y: 1;
                }
                ArcTo {
                    radius-x: 4;
                    radius-y: 4;
                    x-rotation: 0;
                    large-arc: true;
                    sweep: true;
                    x: 5;
                    y: 9;
                }
                ArcTo {
                    radius-x: 4;
                    radius-y: 4;
                    x-rotation: 0;
                    large-arc: true;
                    sweep: true;
                    x: 5;
                    y: 1;
                }
            }

            Path {
                stroke-width: 10px;
                stroke: #e0e0e0;
                viewbox-x: 0;
                viewbox-y: 0;
                viewbox-width: 10;
                viewbox-height: 10;
                
                MoveTo {
                    x: 5;
                    y: 1;
                }
                ArcTo {
                    radius-x: 4;
                    radius-y: 4;
                    x-rotation: 0;
                    large-arc: logout_time > 0.5;
                    sweep: true;
                    x: 5+4*sin(logout_time*360deg);
                    y: 5-4*cos(logout_time*360deg);
                }
            }
        }
    }
}
